# Docker Image
# OpenMPI + OpenCL (NVIDIA) + Slurm + Ganglia
FROM centos
MAINTAINER "Sumin Han @ Satreci (KAIST internship)"
LABEL com.nvidia.volumes.needed="nvidia_driver"

RUN yum -y install epel-release
RUN yum -y update

# OpenMPI Installation
RUN yum install -y which tar perl gcc gcc-c++ make
RUN curl -O https://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-2.1.1.tar.gz \
	&& gunzip -c openmpi-2.1.1.tar.gz | tar xf - \
	&& cd openmpi-2.1.1 \
	&& ./configure --prefix=/usr/local \
	&& make all install
RUN rm -r -f openmpi-2.1.1.tar.gz openmpi-2.1.1

ENV PATH /usr/local/bin:$PATH
ENV LD_LIBRARY_PATH /usr/local/lib:$LD_LIBRARY_PATH

# OpenCL Setting
RUN yum install -y ocl-icd clinfo

RUN mkdir -p /etc/OpenCL/vendors && \
    echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd
 
RUN echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf && \
    echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf
 
ENV PATH /usr/local/nvidia/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64

# OpenSSH Setting (Public Key registeration)
RUN yum install -y openssh-server openssh-clients
RUN ssh-keygen -A
RUN ssh-keygen -f $HOME/.ssh/id_rsa -t rsa -N ''
RUN cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
RUN echo "StrictHostKeyChecking no" >> ~/.ssh/config

# Ganglia Install
RUN yum install -y ganglia-gmond
COPY gmond.conf /etc/ganglia/gmond.conf

# Slurm Installation
RUN groupadd -r slurm && useradd -r -g slurm slurm

#RUN yum -y install epel-release && yum -y update
RUN yum -y install munge munge-libs munge-devel

#RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum -y install wget bzip2 perl perl-devel gcc gcc-cpp vim-enhanced git make munge munge-devel supervisor \
	openssl openssl-devel pam-devel numactl numactl-devel hwloc hwloc-devel lua lua-devel readline-devel rrdtool-devel ncurses-devel man2html libibmad libibumad rpm-build

#ENV SLURM_VERSION 15.08.13
#ENV SLURM_DOWNLOAD_MD5 93d5afd7a18680923b08aefa528ba9db
#ENV SLURM_VERSION 17.02.5
#ENV SLURM_DOWNLOAD_MD5 9bcbddd4bffca6e26b7c03dd96b6f3e2
#ENV SLURM_DOWNLOAD_URL http://www.schedmd.com/downloads/archive/slurm-"$SLURM_VERSION".tar.bz2

RUN mkdir nfs && cd /nfs \
	&& wget http://www.schedmd.com/download/latest/slurm-17.02.6.tar.bz2
RUN cd /nfs && rpmbuild -ta slurm-17.02.6.tar.bz2
RUN cd /root/rpmbuild/RPMS/x86_64 \
    && yum -y --nogpgcheck localinstall *

RUN echo "Done"

RUN yum -y install net-tools libcgroup stress
RUN yum -y install \*cgroup\*
RUN set -x  \
#	&& wget -O slurm.tar.bz2 "$SLURM_DOWNLOAD_URL" \
#	&& echo "$SLURM_DOWNLOAD_MD5" slurm.tar.bz2 | md5sum -c - \
#	&& mkdir /usr/local/src/slurm \
#	&& tar jxf slurm.tar.bz2 -C /usr/local/src/slurm --strip-components=1 \
#    && rm slurm.tar.bz2 \
#    && cd /usr/local/src/slurm \
#    && ./configure --enable-debug --enable-front-end --prefix=/usr --sysconfdir=/etc/slurm \
#    && make install \
#    && install -D -m644 etc/cgroup.conf.example /etc/slurm/cgroup.conf.example \
#    && install -D -m644 etc/slurm.conf.example /etc/slurm/slurm.conf.example \
#    && install -D -m644 etc/slurm.epilog.clean /etc/slurm/slurm.epilog.clean \
#    && install -D -m644 etc/slurmdbd.conf.example /etc/slurm/slurmdbd.conf.example \
    && cd \
    && rm -rf /usr/local/src/slurm \
    && mkdir /etc/sysconfig/slurm \
    && mkdir /var/spool/slurmd \
    && chown slurm:slurm /var/spool/slurmd \
    && mkdir /var/run/slurmd \
    && chown slurm:slurm /var/run/slurmd \
    && mkdir /var/lib/slurmd \
    && chown slurm:slurm /var/lib/slurmd \
    && /sbin/create-munge-key

#RUN yum -y install mesa-libGL-devel mesa-libGLU-devel
RUN wget ftp://sourceware.org/pub/valgrind/valgrind-3.13.0.tar.bz2
RUN tar xvjf valgrind-3.13.0.tar.bz2
RUN cd valgrind-3.13.0 && ./configure && make && make install 

COPY supervisord.conf /etc/
RUN echo alias si=\'sinfo -o \"%20P %5D %14F %8z %10m %10d %11l %16f %N\"\' >> ~/.bashrc \
	&& echo alias si2=\'sinfo -o \"%20P %5D %6t %8z %10m %10d %11l %16f %N\"\' >> ~/.bashrc \
	&& echo alias sq=\'squeue -o \"%8i %12j %4t %10u %20q %20a %10g %20P %10Q %5D %11l %11L %R\"\' >> ~/.bashrc \
	&& echo alias st=\'srun -N5 hostname\' >> ~/.bashrc
RUN mkdir /etc/slurm/cgroup
RUN yum -y install python2-pip && pip install --upgrade pip && pip install ctop

COPY cgroup.conf /etc/slurm/cgroup.conf
COPY slurm.conf /etc/slurm/slurm.conf
#RUN cgroup_enable=memory swapaccount=1

#RUN yum -y install mesa-\*


#ENTRYPOINT /usr/bin/supervisord -c /etc/supervisord.conf && /bin/bash
